### ISSUE TITLE
breaks.pdf: Misleading denomination "Continue for one line"

### ISSUE THREAD

**Issue by PaulChristopher** [rhythms-of-resistance/sheetbook#1]
See  sheetbook/generated/single/breaks.pdf "General breaks", page 1:

"Continue one line" actually means not to play one line of a certain tune, but just one bar / one measure / 4 beats. IMHO "Continue one line" should be called "Continue for one bar (or measure) / 4 beats", see https://en.wikipedia.org/wiki/Bar_(music) .

"One line" - literally speaking as printed in the tune sheet -- could comprise of one bar e. g. in Custard, or several bars e.g. in Bhangra or Afoxe. That's why "line" is confusing, since it reminds the people of the rhythm line printed in the sheet. Calling "Continue One Line" "Continue One Bar" would be more precise.

**Comment by cdauth** [comment]
Good point
