### ISSUE TITLE
Better wording of “0” vs “sil” notation for surdos

### ISSUE THREAD

**Issue by leukoszafir** [rhythms-of-resistance/sheetbook#2]
Hi,

We are not native English speakers and had trouble understanding the difference between "0" and "sil" on surdos. Am I correct in assuming that "0" means hitting the drum only with hand, and "sil" means hitting it with a stick while the hand rests on the skin? Either way, I think the current description ("damped with hand" vs "silent hit (with hand resting on the skin)" is a bit unclear. My proposed wording would be something in the lines of

| 0 | sil |
|---|---|
| hit the drum with hand | hit the drum with a stick with the other hand resting on skin |

except maybe a bit shorter. What do you think?

The current state of affairs:  
![image](https://user-images.githubusercontent.com/54084157/63713371-d6938e00-c83f-11e9-8d97-bfa993d6125b.png)

Edit: AFAIK we could also reuse the explanation for "hd" and "sil" on repis.

**Comment by leukoszafir** [comment]
On a similar note, it'd be nice to have "w" (whippy stick) explained there.

**Comment by cdauth** [comment]
As far as I understand, `0` means to hit the drum with the hand and leave the hand on the drum for a moment, so that it kills (damps) the sound, while `hd` means to hit the drum with the hand in the same way as you would hit it with a stick.

**Comment by leukoszafir** [comment]
TIL! Okay, how about

| 0 | sil |
|---|---|
| hit the drum with hand and leave it on the drum for a moment | hit the drum with a stick with the other hand resting on skin |

I can make a PR tomorrow.

**Comment by cdauth** [comment]
Don't bother about a pull request, it’s easier to put the description in by hand than it is to check a pull request.

**Comment by logarytm** [comment]
Ah, the perils of versioning binary files 😊 Thanks!

**Comment by cdauth** [comment]
I updated the whole notation section, what do you think? See [here](https://github.com/rhythms-of-resistance/sheetbook/blob/master/generated/single/breaks.pdf) at the bottom.
